version: '3.7'

services:
  sonarqube:
    image: sonarqube:6.7.1
    environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=password
    - SONARQUBE_JDBC_URL=jdbc:postgresql://database:5432/sonarqube
    ports:
    - "9000:9000"
    - "9092:9092"
    volumes:
    - ~/projects/perso/sonar/data:/opt/sonarqube/data
    - ~/projects/perso/sonar/extensions:/opt/sonarqube/extensions
    - ~/projects/perso/sonar/conf:/opt/sonarqube/conf
    - ~/projects/perso/sonar/plugins:/opt/sonarqube/lib/bundled-plugins

  database:
    image: postgres:10.1
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=sonarqube
    volumes:
    - ~/projects/perso/sonar/db:/var/lib/postgresql
    - ~/projects/perso/sonar/postgresql:/var/lib/postgresql/data

